Removed DFX_INTERNAL_RESEARCHER role from Apiary
nuralogix/dfxapidocs pull request #53
Opened 2024-07-10 19:07 UTC by Vineet-nuralogix

2024-07-10 19:07 UTC, anmol-nura approved these changes

2024-07-10 19:22 UTC, daphnezhou requested changes
Please also remove user role 'DFX_BASIC_USER' since it's deprecated.

2024-07-10 20:04 UTC, aajoshi1 approved these changes

2024-07-11 20:10 UTC, daphnezhou approved these changes

2024-07-11 20:32 UTC, merged